services:
  attendance:
    build: ./Attendance
    container_name: attendance_server
    env_file:
      - ./Attendance/.env
    restart: always
    ports:
      - "4001:4001"

  customer:
    build: ./Customer
    container_name: customer_server
    env_file:
      - ./Customer/.env
    restart: always
    ports:
      - "4002:4002"


  authentication:
    build: ./Authentication
    container_name: authentication_server
    env_file:
      - ./Authentication/.env
    restart: always
    ports:
      - "4003:4003"     
       